# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- name: TargetsPath
  value: /Users/gamu/.azuredatastudio/extensions/microsoft.sql-database-projects-1.2.0/BuildDirectory 
- name: AppName
  value: SqlDatabaseProject

trigger:
- master

pool:
  name: OnpremPool
  demands:
  - Agent.Version -equals 3.220.5

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/SqlServerDatabase/SqlServerDatabase.sqlproj'
    arguments: '--configuration Release --output $(Build.BinariesDirectory)  /p:NetCoreBuild=true /p:NETCoreTargetsPath=$(TargetsPath)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(AppName)_$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(AppName)_$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
