trigger:
- '*'

pool:
  vmImage: vs2017-win2016
  demands: msbuild


steps:
- task: MSBuild@1
  displayName: 'Build solution SqlServerDatabase.sln'
  inputs:
    solution: SqlServerDatabase.sln
    configuration: Release
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SQL'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: SQL


