# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: OnpremPool
  demands:
  - Agent.Version -equals 3.220.5

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/SqlServerDatabase/SqlServerDatabase.sqlproj'
    arguments: '--configuration Release  /p:NetCoreBuild=true /p:NETCoreTargetsPath=$(TARGET_PATH)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
